import { createClient } from '@/lib/supabase/server'
import { notFound } from 'next/navigation'
import { US_STATES, STATE_LAWS, formatCurrency, formatDate } from '@/lib/utils'

export default async function LeasePrintPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  const { data: lease } = await supabase
    .from('leases')
    .select('*, tenants(first_name, last_name, email, phone), properties(name, address, city, state, zip), profiles!owner_id(full_name, email, phone)')
    .eq('id', id)
    .eq('owner_id', user!.id)
    .single()

  if (!lease) notFound()

  const profile = Array.isArray(lease.profiles) ? lease.profiles[0] : lease.profiles
  const stateLaw = STATE_LAWS[lease.state]
  const stateName = US_STATES.find(s => s.code === lease.state)?.name || lease.state

  return (
    <html>
      <head>
        <title>Lease Agreement — {lease.tenants?.first_name} {lease.tenants?.last_name}</title>
        <style>{`
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: 'Times New Roman', serif; font-size: 11pt; line-height: 1.6; color: #000; background: white; padding: 1in; max-width: 8.5in; margin: 0 auto; }
          h1 { font-size: 16pt; text-align: center; margin-bottom: 6pt; font-weight: bold; }
          h2 { font-size: 13pt; margin: 18pt 0 6pt; font-weight: bold; border-bottom: 1px solid #000; padding-bottom: 3pt; }
          h3 { font-size: 11pt; margin: 12pt 0 4pt; font-weight: bold; }
          p { margin-bottom: 8pt; }
          .center { text-align: center; }
          .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8pt; margin-bottom: 12pt; }
          .field { margin-bottom: 6pt; }
          .label { font-weight: bold; font-size: 10pt; }
          .value { border-bottom: 1px solid #666; min-width: 120px; display: inline-block; padding: 0 4pt; }
          .sig-block { margin-top: 32pt; display: grid; grid-template-columns: 1fr 1fr; gap: 24pt; }
          .sig-line { border-top: 1px solid #000; margin-top: 40pt; padding-top: 4pt; font-size: 10pt; }
          @media print { body { padding: 0; } @page { margin: 1in; } }
        `}</style>
      </head>
      <body>
        <h1>RESIDENTIAL LEASE AGREEMENT</h1>
        <p className="center" style={{textAlign:'center', marginBottom:'16pt', fontSize:'10pt', color:'#444'}}>
          State of {stateName} · Generated by REALESTATEos
        </p>

        <h2>Parties</h2>
        <div className="grid">
          <div>
            <p><strong>LANDLORD:</strong><br />
            {profile?.full_name || 'Landlord'}<br />
            {profile?.email}<br />
            {profile?.phone}
            </p>
          </div>
          <div>
            <p><strong>TENANT:</strong><br />
            {lease.tenants?.first_name} {lease.tenants?.last_name}<br />
            {lease.tenants?.email}<br />
            {lease.tenants?.phone}
            </p>
          </div>
        </div>

        <h2>Property</h2>
        <p>
          <strong>Address:</strong> {lease.properties?.address}, {lease.properties?.city}, {lease.properties?.state} {lease.properties?.zip}<br />
          <strong>Property Name:</strong> {lease.properties?.name}
        </p>

        <h2>Lease Terms</h2>
        <div className="grid">
          <p><strong>Lease Type:</strong> {lease.lease_type === 'month_to_month' ? 'Month-to-Month' : 'Fixed Term'}</p>
          <p><strong>Start Date:</strong> {formatDate(lease.start_date)}</p>
          {lease.end_date && <p><strong>End Date:</strong> {formatDate(lease.end_date)}</p>}
          <p><strong>Monthly Rent:</strong> {formatCurrency(lease.monthly_rent)}</p>
          <p><strong>Rent Due Day:</strong> {lease.rent_due_day}{['st','nd','rd'][lease.rent_due_day - 1] || 'th'} of each month</p>
          <p><strong>Security Deposit:</strong> {formatCurrency(lease.security_deposit)}</p>
          <p><strong>Late Fee:</strong> {formatCurrency(lease.late_fee)} after {lease.late_fee_days} days</p>
        </div>

        <h2>State-Specific Terms ({stateName})</h2>
        {stateLaw ? (
          <div>
            <p><strong>Notice to Pay or Quit:</strong> {stateLaw.noticePay}</p>
            <p><strong>Entry Notice Required:</strong> {stateLaw.entryNotice}</p>
            <p><strong>Security Deposit Maximum:</strong> {stateLaw.depositMax}</p>
            <p><strong>Deposit Return Deadline:</strong> {stateLaw.depositReturn}</p>
            <p><strong>Maximum Late Fee:</strong> {stateLaw.lateFeeMax}</p>
            {stateLaw.rentControl && <p><strong>Rent Control:</strong> This property may be subject to local rent control ordinances. Verify with local authorities.</p>}
          </div>
        ) : (
          <p>Standard landlord-tenant laws apply. Consult your state&apos;s landlord-tenant statute for specific requirements.</p>
        )}

        <h2>General Provisions</h2>
        <h3>1. Payment</h3>
        <p>Tenant agrees to pay {formatCurrency(lease.monthly_rent)} per month as rent, due on the {lease.rent_due_day}{['st','nd','rd'][lease.rent_due_day - 1] || 'th'} day of each month. Rent shall be paid to Landlord via the tenant portal or other agreed method. A late fee of {formatCurrency(lease.late_fee)} will be assessed if rent is not received within {lease.late_fee_days} days of the due date.</p>

        <h3>2. Security Deposit</h3>
        <p>Tenant has paid a security deposit of {formatCurrency(lease.security_deposit)}. The deposit will be held and returned in accordance with {stateName} law. Landlord may deduct from the deposit amounts necessary to remedy unpaid rent or damages beyond normal wear and tear.</p>

        <h3>3. Occupancy &amp; Use</h3>
        <p>The premises shall be occupied only as a private residence. Tenant shall not sublet the premises or assign this lease without prior written consent from Landlord.</p>

        <h3>4. Maintenance &amp; Repairs</h3>
        <p>Landlord shall maintain the premises in habitable condition. Tenant shall promptly notify Landlord of any defects or necessary repairs. Tenant shall be responsible for damage caused by Tenant&apos;s negligence.</p>

        <h3>5. Entry by Landlord</h3>
        <p>Landlord shall provide {stateLaw?.entryNotice || '24 hours'} advance notice before entering the premises, except in cases of emergency.</p>

        <h3>6. Default</h3>
        <p>If Tenant fails to pay rent when due, Landlord may provide written notice to pay or quit in accordance with {stateName} law. Continued default may result in eviction proceedings.</p>

        {lease.notes && (
          <>
            <h2>Additional Terms</h2>
            <p style={{whiteSpace: 'pre-wrap'}}>{lease.notes}</p>
          </>
        )}

        <div className="sig-block">
          <div>
            <div className="sig-line">Landlord Signature</div>
            <p style={{marginTop:'6pt'}}>{profile?.full_name || 'Landlord'}</p>
            <div className="sig-line" style={{marginTop:'24pt'}}>Date</div>
          </div>
          <div>
            <div className="sig-line">Tenant Signature</div>
            <p style={{marginTop:'6pt'}}>{lease.tenants?.first_name} {lease.tenants?.last_name}</p>
            <div className="sig-line" style={{marginTop:'24pt'}}>Date</div>
          </div>
        </div>

        <p style={{marginTop:'32pt', fontSize:'9pt', textAlign:'center', color:'#666'}}>
          This lease was generated by REALESTATEos. This document should be reviewed by a licensed attorney.
        </p>
      </body>
    </html>
  )
}
