/** Heuristic draft for landlord review — not legal advice. Tier-3 can swap in LLM + state templates. */
export function draftCollectionsNotice(input: {
  state: string
  tenantName: string
  amount: number
  daysLate: number
  tone: 'friendly' | 'neutral' | 'firm'
}): string {
  const { state, tenantName, amount, daysLate, tone } = input
  const amt = amount.toFixed(2)
  const open =
    tone === 'firm'
      ? `This is a formal notice regarding past-due rent at the leased premises in ${state}.`
      : tone === 'neutral'
        ? `We are writing about rent that is now past due for your tenancy in ${state}.`
        : `Hi ${tenantName}, we wanted to reach out about the rent balance before it becomes a bigger issue.`

  return `${open}

Tenant: ${tenantName}
Amount past due: $${amt}
Days late (approx.): ${daysLate}

Next steps: Confirm payment date, or contact us immediately if there is a dispute. Have an attorney review any pay-or-quit or eviction notices — requirements vary by ${state} and locality.

— Generated by RealEstateOS (draft only, not served as legal notice)`
}
